### ISSUE TITLE
Does it support native HomeKit devices

### ISSUE THREAD

**Issue by maisun** [NorthernMan54/node-red-contrib-homebridge-automation#8]
Hi,

Thanks for the effort! Does the automation support native HomeKit accessaries (not added via HomeBridge)? Thanks!

**Comment by b2un0** [comment]
I think no. i switched for my part all HomeKit certified devices to Homebridge (like Yeelights, Hue and Aqara).

**Comment by NorthernMan54** [comment]
Sorry it does not support native HomeKit.

**Comment by maisun** [comment]
ok, thanks for the quick reply!

**Comment by tthoma24** [comment]
What would it take to make this project support Homekit-native devices?

**Comment by NorthernMan54** [comment]
It would take Apple removing HomeKit security from their devices. Which would never happen.

**Comment by tthoma24** [comment]
I'm a little confused what you mean by "removing homekit security", can you explain a little further? It's my understanding that you no longer need specific hardware requirements in order to interact with HomeKit devices, as there is now a non-commercial software based HAP spec, and it should in theory be possible to add support to this project through that. Am I missing something?

**Comment by NorthernMan54** [comment]
With native HomeKit devices you can only pair them ‘once’ per house, and with homebridge I’m able to bypass that restriction.  You can find more details by reading the HAP spec
